data = {'a': 1, 'b':2, 'c':3} # cria uma dicionário com key-values
print(data['a', 'b']) # tenta acessar os elementos em 'data' usando tuplas 'a' e 'b'. Como a tupla ('a', 'b') não existe como chave no dicionário de dados, um KeyError é gerado.

# >> KeyError: ('a', 'b')
#  The code is erroneous.
